name: CI

on:
  push:
    branches: ["carlosClaure_p2_dev", "carlosClaure_p2_base"]
  pull_request:
    branches: ["carlosClaure_p2_base"]

  workflow_dispatch:

env:
  SEM_VERSION: ""
  IMAGE_NAME: ""

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python Virtual Environment (Poetry)
        uses: DarylStark/actions-python-venv-poetry@dev
        with:
          python-version: "3.11"

      - name: Checking python version
        run: |
          python --version
          python3 --version
          pip --version
          pip3 --version

  static-codecheck:
    runs-on: self-hosted
    steps:
      - name: Printing job
        uses: echo "Static-codecheck job"

  deploy-dev:
    runs-on: self-hosted
    needs: build
    environment:
      name: Develop
      url: http://localhost:5000

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  deploy-prod:
    runs-on: self-hosted
    needs: deploy-dev
    environment:
      name: Production
      url: http://localhost:5000

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
