name: CI

on:
  push:
    branches: ["carlosClaure_p2_dev", "carlosClaure_p2_base"]
  pull_request:
    branches: ["carlosClaure_p2_base"]

  workflow_dispatch:

jobs:
  static-codecheck:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: python3 -m pytest test/unit -v

  build:
    runs-on: self-hosted
    needs: static-codecheck
    # environment: ${{ matrix.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t ${{ vars.IMAGE_NAME }}:${{ github.sha }} .

      - name: Tag Docker Image
        run: |
          docker tag ${{vars.IMAGE_NAME}}:${{github.sha}} cclaurevju/${{vars.IMAGE_NAME}}:${{github.sha}}

    # strategy:
    #   matrix:
    #     environment: [Develop, Production]

  push-to-registry:
    runs-on: self-hosted
    needs: build
    # environment: Production
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push to Docker Hub
        run: |
          docker push cclaurevju/${{ vars.IMAGE_NAME }}:${{ github.sha }}

  deploy-dev:
    runs-on: self-hosted
    needs: push-to-registry
    environment: Develop

    steps:
      - name: Stop and Remove Existing Containers
        run: |
          docker stop ${{ vars.CONTAINER_NAME }} || true
          docker rm ${{ vars.CONTAINER_NAME }} || true
          docker stop ${{ vars.REDIS_SERVICE_NAME }} || true
          docker rm ${{ vars.REDIS_SERVICE_NAME }} || true

      - name: Run Docker compose
        run: |
          docker compose run --env CONTAINER_NAME=${{vars.CONTAINER_NAME}} --env FLASK_PORT=${{vars.FLASK_PORT}} --env VERSION=${{ github.sha }} --env REDIS_PORT=${{vars.REDIS_PORT}}

      # - name: Deploy Redis Container Development
      #   run: |
      #     docker run --name ${{ vars.REDIS_SERVICE_NAME }} -p ${{ vars.REDIS_PORT }}:6379 -d redis:alpine

      # - name: Deploy to Docker Development
      #   run: |
      #     docker run -d -p ${{ vars.FLASK_PORT }}:5000 --add-host redis:$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${{ vars.REDIS_SERVICE_NAME }}) --name ${{ vars.CONTAINER_NAME }} ${{ vars.IMAGE_NAME }}:${{ github.sha }}

  test:
    runs-on: self-hosted
    needs: deploy-dev
    environment: Develop
    steps:
      - name: Testing Redis Connection
        run: |
          docker exec ${{ vars.CONTAINER_NAME }} sh -c "python -m pytest test/integration -v"

  deploy-prod:
    if: github.ref == 'refs/heads/carlosClaure_p2_base'
    runs-on: self-hosted
    needs: test
    environment: Production
    steps:
      - name: Stop and Remove Existing Containers
        run: |
          docker stop ${{ vars.CONTAINER_NAME }} || true
          docker rm ${{ vars.CONTAINER_NAME }} || true
          docker stop ${{ vars.REDIS_SERVICE_NAME }} || true
          docker rm ${{ vars.REDIS_SERVICE_NAME }} || true

      - name: Deploy Redis Container Production
        run: |
          docker run --name ${{ vars.REDIS_SERVICE_NAME }} -p ${{ vars.REDIS_PORT }}:6379 -d redis:alpine

      - name: Deploy to Docker Production
        run: |
          docker run -d -p ${{ vars.FLASK_PORT }}:5000 --add-host redis:$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${{ vars.REDIS_SERVICE_NAME }}) --name ${{ vars.CONTAINER_NAME }} ${{ vars.IMAGE_NAME }}:${{ github.sha }}
