name: CI

on:
  push:
    branches: ["carlosClaure_p2_dev", "carlosClaure_p2_base"]
  pull_request:
    branches: ["carlosClaure_p2_base"]

  workflow_dispatch:

env:
  SEM_VERSION: ""
  IMAGE_NAME: ""

jobs:
  build:
    runs-on: self-hosted
    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t ${{ vars.IMAGE_NAME }}:${{ github.sha }} .
    strategy:
      matrix:
        environment: [Develop, Production]

  deploy-dev:
    runs-on: self-hosted
    needs: build
    environment: Develop

    steps:
      - name: Stop and Remove Existing Containers
        run: |
          docker stop ${{ vars.CONTAINER_NAME }} || true
          docker rm ${{ vars.CONTAINER_NAME }} || true
          docker stop ${{ vars.REDIS_SERVICE_NAME }} || true
          docker rm ${{ vars.REDIS_SERVICE_NAME }} || true

      - name: Deploy Redis Container Development
        run: |
          docker run --name ${{ vars.REDIS_SERVICE_NAME }} -p ${{ vars.REDIS_PORT }}:6379 -d redis:alpine

      - name: Deploy to Docker Development
        run: |
          docker run -d -p ${{ vars.FLASK_PORT }}:5000 --add-host redis:$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${{ vars.REDIS_SERVICE_NAME }}) --name ${{ vars.CONTAINER_NAME }} ${{ vars.IMAGE_NAME }}:${{ github.sha }}

  test:
    runs-on: self-hosted
    needs: deploy-dev
    environment: Develop
    steps:
      - name: Testing Docker Image
        run: docker exec ${{ vars.CONTAINER_NAME }} sh -c "python -m pytest test/unit -v"

      - name: Testing Redis Connection
        run: |
          docker exec ${{ vars.CONTAINER_NAME }} sh -c "python -m pytest test/integration -v"

  deploy-prod:
    runs-on: self-hosted
    needs: test
    environment: Production

    steps:
      - name: Stop and Remove Existing Containers
        run: |
          docker stop ${{ vars.CONTAINER_NAME }} || true
          docker rm ${{ vars.CONTAINER_NAME }} || true
          docker stop ${{ vars.REDIS_SERVICE_NAME }} || true
          docker rm ${{ vars.REDIS_SERVICE_NAME }} || true

      - name: Deploy Redis Container Production
        run: |
          docker run --name ${{ vars.REDIS_SERVICE_NAME }} -p ${{ vars.REDIS_PORT }}:6379 -d redis:alpine

      - name: Deploy to Docker Production
        run: |
          docker run -d -p ${{ vars.FLASK_PORT }}:5000 --add-host redis:$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${{ vars.REDIS_SERVICE_NAME }}) --name ${{ vars.CONTAINER_NAME }} ${{ vars.IMAGE_NAME }}:${{ github.sha }}
